### ISSUE TITLE
[Feature Request] Support path arguments to js modules

### ISSUE THREAD

**Issue by SuggonM** [seiya-dev/spine2json#2]
Scripts in question:
1. [parse-spine-skel.mjs](scripts/parse-spine-skel.mjs#L6-L25) (Line 6, 16, 25)
2. [patch-atlas-json.mjs](scripts/patch-atlas-json.mjs#L5-L24) (Line 5, 15, 24)
3. and maybe [patch-spine-json.mjs](https://github.com/seiya-dev/spine2json/blob/main/scripts/patch-spine-json.mjs) too

Now that there is [`%_XDIR%`](https://github.com/seiya-dev/spine2json/blob/main/batconfigs.bat#L37), I think it's better to modify the scripts so that they ***only*** rely on paths specified in arguments. For example,
`NODE ./scripts/parse-spine-skel ./assets/admiral/illust_admiral` to write `illust_admiral.s2j.json` into path `./assets/admiral/`

So in terms of scripting, that'd roughly be:
```js
import { dirname, basename } from 'path';

const args = process.argv;

const fullPath = args[2];
const filePrefix = dirname(fullPath);
const fileName = basename(fullPath);
```

**Comment by seiya-git** [comment]
Fixed in #4
